development:
  adapter: mysql2
  database: geocms
  login: geocms
  password: geocms
  #socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: geocms
  login: geocms
  password: geocms
  #socket: /tmp/mysql.sock
