development:
  adapter: mysql2
  database: geocms_dotgee_dev
  login: root
  password: jefedroi
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: geocms_dotgee
  login: root
  password: jefedroi
  socket: /var/run/mysqld/mysqld.sock
